### ISSUE TITLE
base image `ubuntu/xenial64` causes provisioning to fail

### ISSUE THREAD

**Issue by TattdCodeMonkey** [lau/vagrant_elixir#3]
The base image `ubuntu/xenial64` changed the user from `vagrant` to `ubuntu` see [issue here](https://bugs.launchpad.net/cloud-images/+bug/1569237) 

The effect of this is provisioning fails when using this example. You should consider changing the base image. I might have a suggestion after I get one to work.

**Comment by lau** [comment]
Hi. Thanks for pointing that out. The script has been updated to reflect the change.
